[tool.poetry]
name = "pureskillgg-dsdk"
version = "1.2.0"
description = "Python Data Science Development Kit."
authors = ["PureSkill.gg <contact@pureskill.gg>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/pureskillgg/dsdk"
repository = "https://github.com/pureskillgg/dsdk"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.12.32"
pandas = "^1.2.1"
python-rapidjson = "^1.6"
pyarrow = "14.0.*"
structlog = "^22.1.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pylint = "^2.4.0"
pytest = "^7.1.1"
pytest-cov = "^4.0.0"
pytest-runner = "^6.0.0"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry>=1.2"]
build-backend = "poetry.masonry.api"
